=== LegendTianjin/Multi-Document-Summarization/Forum Summarization 2017/ofs17-traindata/ofs17-traindata/en/ofs.dtd
<!ELEMENT document (articleText,commentaries,links)>
<!ELEMENT articleText (s+)>
<!ELEMENT s (#PCDATA)>

<!ELEMENT commentaries (comment+)>
<!ELEMENT comment (s+,comment*)>

<!ELEMENT links (link*)>
<!ELEMENT link (argument,sentiment)>
<!ELEMENT argument (#PCDATA)>
<!ELEMENT sentiment (#PCDATA)>

<!ATTLIST document id ID #REQUIRED>
<!ATTLIST s id ID #REQUIRED>
<!ATTLIST comment id ID #REQUIRED>
<!ATTLIST comment bloggerId CDATA #REQUIRED>
<!ATTLIST link id ID #REQUIRED>
<!ATTLIST link com_sentence IDREF #IMPLIED>
<!ATTLIST link art_sentence IDREF #IMPLIED>
<!ATTLIST argument label (in_favour | impartial | against | not_applicable) "not_applicable">
<!ATTLIST sentiment label (positive | neutral | negative | not_applicable) "not_applicable">

=== LegendTianjin/Multi-Document-Summarization/Forum Summarization 2017/ofs17-testdata/ofs17-testdata/en/en-10.ofs.in.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE document SYSTEM "ofs.dtd">
<document id="articleCommentBartInput10">
<articleText>
<s id="s0"></s>
<s id="s1">Waste . </s>
<s id="s2">Fatberg ahead ! </s>
<s id="s3">How London was saved from a 15-tonne ball of grease . </s>
<s id="s4">Team of sewerage workers took three weeks to clear bus-sized toxic ball of fat that threatened to flood streets with sewage Link to video : &apos; Fatberg &apos; the size of a bus clogs London sewer A sewage worker has become an unlikely hero after taking three weeks to defeat a toxic 15-tonne ball of congealed fat the size of a bus that came close to turning parts of the London borough of Kingston upon Thames into a cesspit . </s>
<s id="s5">The first sign of trouble came when residents in a block of flats near the royal borough &apos;s main sewer reported difficulty flushing their toilets . </s>
<s id="s6">Gordon Hailwood and his team found a &quot;fatberg &quot; of solidified grease and oil blocking 95 % of the 2.4 metre diameter brick sewer pipe . </s>
<s id="s7">It took three weeks working in foul conditions to clear with high powered water jets . </s>
<s id="s8">&quot; Kingston came very close to being flooded with sewage . </s>
<s id="s9">We have recorded greater volumes of fat in the past but we do n&apos;t believe there &apos;s ever been a single congealed lump of lard matching this one&quot; , said Simon Evans , a Thames Water spokesman . </s>
<s id="s10">Fatbergs build up on sewer roofs like mushy stalactites . </s>
<s id="s11">&quot; I have witnessed one . </s>
<s id="s12">It &apos;s a heaving , sick-smelling , rotting mass of filth and faeces . </s>
<s id="s13">It hits the back of your throat , it &apos;s gross , &quot; said Evans . </s>
<s id="s14">&quot; It &apos;s steaming and it unleashes an unimaginable stink . </s>
<s id="s15">Hailwood and his team certainly saved Kingston from a terrible fate . </s>
<s id="s16">&quot; Water and sewage companies say fatbergs are becoming more common . </s>
<s id="s17">London , with the highest concentration of food businesses in the country , produces an estimated 32m-44m litres of used cooking oil every year , much of which is poured down drains . </s>
<s id="s18">Also , the use of wet wipes as toilet paper is increasing , with potentially disastrous results below ground . </s>
<s id="s19">Thames Water says it has to clear nearly 40,000 blockages a year caused by fat and sanitary wipes being wrongly put down drains by restaurants and households . </s>
<s id="s20">&quot; We have 59,000 miles of sewer and fat and wet wipes are the main partners in &apos;sewer abuse &apos; crime , &quot; said Evans . </s>
<s id="s21">&quot; The wipes break down and collect on joints and then the fat congeals . </s>
<s id="s22">Then more fat builds up . </s>
<s id="s23">It &apos;s getting worse . </s>
<s id="s24">More wet wipes are being used and flushed . </s>
<s id="s25">It took Hailwood and the guys three weeks to flush this one out with high-powered water jets . </s>
<s id="s26">&quot; Given we &apos;ve got the biggest sewers and this is the biggest fatberg we &apos;ve encountered , we reckon it has to be the biggest such berg in British history , &quot; said Hailwood . </s>
<s id="s27">&quot; The sewer was almost completely clogged . </s>
<s id="s28">If we had n&apos;t discovered it in time , raw sewage could have started spurting out of manholes across the whole of Kingston . </s>
<s id="s29">It was so big it damaged the sewer and repairs will take up to six weeks . </s>
<s id="s30">&quot; However ? </s>
<s id="s31">in what environmental groups call a &quot;win-win &quot; development ? </s>
<s id="s32">waste fat is now being used to generate renewable energy . </s>
<s id="s33">McDonald &apos;s collects more than 600,000 litres of used cooking oil from its London restaurants each year , converting it to biodiesel to run half its fleet of lorries . </s>
<s id="s34">London mayor Boris Johnson is pressing for waste fat to be used to run London &apos;s buses . </s>
<s id="s35">&quot; By capturing it right here in London and turning it into biodiesel we could provide 20 % of the fuel needed to power London &apos;s entire bus fleet while saving thousands of tonnes of CO2 and creating hundreds of new jobs . </s>
<s id="s36">There is huge potential to unlock the value in used cooking oil and turn it to our economic advantage , &quot; Johnson said last week . </s>
<s id="s37">One consortium plans to generate 130 gigawatt hours ( GWh ) of renewable electricity each year ? </s>
<s id="s38">enough to run 39,000 average homes ? </s>
<s id="s39">by burning 30 tonnes a day of fat , oil and grease . </s>
<s id="s40">The oils will be collected from food outlets and manufacturers , and solidified grease will be harvested from &quot;fat traps &quot; installed in restaurant , hospital , stadium and factory kitchens . </s>
<s id="s41">Thames Water has agreed to buy half the electricity to run London &apos;s largest sewerage works at Beckton . </s>
<s id="s42">Keeping drains clear ? </s>
<s id="s43">Animal fats and vegetable oil , lard , grease , butter and margarine , food scraps and dairy products all contribute to blocked drains , &quot;fatbergs &quot; and sewer blockages . </s>
<s id="s44">Waste disposal units do not remove fats . </s>
<s id="s45">? </s>
<s id="s46">Wipes , nappies , sanitary towels , rags and condoms do not break down easily and can snag on pipes , drains and the walls of sewers , leading to blockages . </s>
<s id="s47">? </s>
<s id="s48">Pesticides , battery acids , nail polish , motor oil , chlorine-based and other cleaning products , paints and photographic chemicals are all toxic waste and should be disposed of carefully because they do not break down in sewage systems and can pollute rivers and sea water . </s>
<s id="s49">? </s>
<s id="s50">If you have a septic tank , then be extra careful . </s>
<s id="s51">Do n&apos;t flush medicines , coffee grounds , paper towels or egg shells , or anything that breaks down slowly , down the toilet or sink . </s>
<s id="s52">? </s>
<s id="s53">This article was amended on 8 August 2013 . </s>
<s id="s54">An earlier version referred to chlorine , rather than chlorine-based , cleaning products . </s>
</articleText>
<commentaries>
<comment id="c0" bloggerId="PatriciaPJ">
<s id="s55">[PatriciaPJ] What heroes those men are , they deserve a serious reward . </s>
<comment id="c1" bloggerId="JulianG">
<s id="s56">[ JulianG] Alas , they are probably on zero hour contracts . </s>
<s id="s57">And treated like shit . </s>
<comment id="c2" bloggerId="AShortFuse">
<s id="s58">[AShortFuse ] to be fair , all the shit in the sewer is treated .... so they probably are treated much like the shit is </s>
</comment>
<comment id="c3" bloggerId="almorr">
<s id="s59">[almorr ] No, they are heroes and are not on zero contracts </s>
</comment>
<comment id="c4" bloggerId="horse69outside">
<s id="s60">[horse69outside ] its a shit business </s>
</comment>
<comment id="c5" bloggerId="IvanDrago1">
<s id="s61">[IvanDrago1 ] I struggle to change my babys nappy , These guys must be super human ! </s>
<s id="s62">My hat goes off to you , Thank you ! </s>
</comment>
</comment>
<comment id="c6" bloggerId="iamnotwise">
<s id="s63">[iamnotwise ] They &apos;re like human statins . </s>
<comment id="c7" bloggerId="MrHeathcliff">
<s id="s64">[MrHeathcliff ] That &apos;s a good one -- I &apos;m going to give you an LOL </s>
</comment>
<comment id="c8" bloggerId="farabundovive">
<s id="s65">[farabundovive ] They &apos;re like human statins . </s>
<s id="s66">Hopefully , without the same nasty side-effects </s>
</comment>
<comment id="c9" bloggerId="Mischieftess">
<s id="s67">[Mischieftess ] Well , statins do n&apos;t work to break down and remove cholesterol and plaques . </s>
<s id="s68">Instead , they inhibit an enzyme ( HMG-CoA-reductase ) that produces cholesterol in your cells , thus reducing further damage from high cholesterol levels . </s>
<s id="s69">To fix atherosclerosis , there are surgeries and other medications , but you really do n&apos;t want to flush loose chunks of plaque into your arteries - they will get trapped in narrowing arteries ( like coronaries of the heart ) and cause infarcts . </s>
<s id="s70">A more apt analogy may be that these people are &quot;like human laxatives . &quot; </s>
</comment>
<comment id="c10" bloggerId="rustlebland">
<s id="s71">[rustlebland ] or human wire coathangers </s>
</comment>
</comment>
<comment id="c11" bloggerId="Dunnyboy">
<s id="s72">[ Dunnyboy ] They should get the Order of the Bath . </s>
<comment id="c12" bloggerId="fflump">
<s id="s73">[fflump ] They should get the Order of the Bath . </s>
<s id="s74">That or the Order of the Brown Nose . </s>
</comment>
<comment id="c13" bloggerId="Hartabuna">
<s id="s75">[ Hartabuna ] Or at least one may say that for these guys a bath is in order ..... </s>
</comment>
</comment>
<comment id="c14" bloggerId="londonnites123">
<s id="s76">[londonnites123 ] I agree . </s>
<s id="s77">Those sewage workers work day and night to ensure giant fatburgers do not destroy our way of life . </s>
<s id="s78">Also David Cameron should consider ex lax when he is that blocked up and has to go to the restroom . </s>
<s id="s79">Jus &apos; sayin ... </s>
</comment>
<comment id="c15" bloggerId="FreakyChucker1">
<s id="s80">[ FreakyChucker1 ] Could n&apos;t agree more . </s>
<s id="s81">I live in Kingston ! </s>
<s id="s82">They should get whatever the ghostbusters got - a open-top bus parade through Kingston at the very least . </s>
<s id="s83">I like to think that &apos;s basically what these guys are , the ghostbusters , but with giant , bus-sized globules of disgusting , stinking , steaming ( ! ) rancid , shit-filled grease instead of , you know , ghosts . </s>
<s id="s84">In fact , I reckon I &apos;d rather face actual ghosts than what &apos;s been described here . </s>
